### ISSUE TITLE
Loading Screen

### ISSUE THREAD

**Issue by code-wizard** [just1and0/React-Native-Paystack-WebView#13] opened 2020-03-26 14:12 UTC
I tried using this library with react-native expo. After setting up all the configuration when I load the webview it keeps showing the loader without any feedback. 
This is the example I used
```
<View style={{flex: 1}}>
        <PaystackWebView
          showPayButton={false}
          paystackKey="MY_OWN_KEY"
          amount={120000}
          billingEmail="paystackwebview@something.com"
          billingMobile="09787377462"
          billingName="Oluwatobi Shokunbi"
          ActivityIndicatorColor="green"
          SafeAreaViewContainer={{marginTop: 5}}
          SafeAreaViewContainerModal={{marginTop: 5}}
          onCancel={() => {  alert('cancelled'); }}
          onSuccess={() => {  alert('success'); }}
           ref={childRef}
        /> <TouchableOpacity onPress={()=> childRef.current.StartTransaction()}>
             <Text>pay now</Text>
						<TouchableOpacity/>
      </View>
```

**Comment by just1and0** [comment] 2020-03-26 14:16
Hi!
could your share the react-native version used? and any other version number used for your project so i can test on my end?

**Comment by code-wizard** [comment] 2020-03-26 14:29
@just1and0 thanks for the swift response
react-native: 0.59.8
expo: ^35.0.0
React-Native-Paystack-WebView: 3.0.3

**Comment by Somtozech** [comment] 2020-04-03 19:46
having the same issue too

**Comment by rebirthtobi** [comment] 2020-04-04 21:50
I don't think this is particular to expo,

I see a blank screen on
react-native: 0.61.5
React-Native-Paystack-WebView: 3.0.4

**Comment by rebirthtobi** [comment] 2020-04-05 19:48
> I don't think this is particular to expo,
> 
> I see a blank screen on
> react-native: 0.61.5
> React-Native-Paystack-WebView: 3.0.4

i figure out that i was passing a null as email not knowing that it is required. it will be better if this is specified in the readMe

**Comment by GideonAgboba** [comment] 2020-05-08 12:31
please can some one help with the requirements for 
react-native-paystack-webview 3.0.6 to run perfectly with expo

**Comment by just1and0** [comment] 2020-05-12 23:39
could you use v3.0.1 of React-Native-Paystack-WebView instead?

**Comment by habibkayode123** [comment] 2020-05-14 09:14
I am also seeing blank screen and I have try v3.0.1

**Comment by just1and0** [comment] 2020-05-14 15:25
What’s your React Native and react native webview version ?

**Comment by Remig9** [comment] 2020-05-15 14:00
am parsing in my refNumber but getting another number after successful payment , pls help

**Comment by dayaki** [comment] 2020-05-28 01:16
@just1and0 mine is stuck on white blank screen after the loading indicator. React Native v0.61 and react native webview 8.1.1

**Comment by Somtozech** [comment] 2020-05-28 14:43
> @just1and0 mine is stuck on white blank screen after the loading indicator. React Native v0.61 and react native webview 8.1.1

Sometimes this happens when the data you passed to the modal is undefined. Make sure whatever you passing is not undefined

**Comment by dayaki** [comment] 2020-05-28 15:09
Everything was hard-coded to test, and it still fails. Maybe @just1and0  should indicate the required fields

**Comment by Oguntoye** [comment] 2020-05-28 19:44
@just1and0 .. The white screen seems to be a general problem.. 
I've tried both libraries suggested by paystack for react native...None seems to works as expected.

**Comment by dayaki** [comment] 2020-05-28 20:02
I have been able to modify this package to make it work with latest expo and webview, will try share soon

**Comment by aripuzo** [comment] 2020-06-04 08:43
I stuck here too, blank screen after hardcoding prop values

**Comment by saladinjake** [comment] 2020-06-04 16:33
i was able to get it out of the blank screen but i get a message we could not start this transaction. this transaction is either invalid or already completed. please confirm that the link is correct

**Comment by Remig9** [comment] 2020-06-04 16:35
You have to change the reference id

**Comment by saladinjake** [comment] 2020-06-04 17:19
i autogenerate a ref id all the time

**Comment by saladinjake** [comment] 2020-06-04 17:23
i i use a shortid library. but it still throws the same exception error. here is my code snippet

`<PaystackWebView
           buttonText="Pay Now"
           showPayButton={true}
          paystackKey="key is publick key"
          amount={12000}
          billingEmail="juwavictor@gmail.com"
          billingMobile="08068291106"
          billingName="mongodbname-for my client-is not known"
          ActivityIndicatorColor="green"
          SafeAreaViewContainer={{marginTop: 25}}
          SafeAreaViewContainerModal={{marginTop: 25}}
          onCancel={() => {  alert('cancelled'); }}
          onSuccess={() => {  alert('success'); }}
          autoStart={false}
          refNumber={shortid.generate()}
        /> `

**Comment by saladinjake** [comment] 2020-06-04 17:25
please i need help. how do i get out of this? is there a code snippet to solve these reference id?

**Comment by Remig9** [comment] 2020-06-04 17:31
Comment the refNumber out and see if it works

**Comment by saladinjake** [comment] 2020-06-04 17:34
OK

**Comment by saladinjake** [comment] 2020-06-04 17:34
Trying it out just now

**Comment by saladinjake** [comment] 2020-06-04 17:37
same issue. didnt work for me

**Comment by saladinjake** [comment] 2020-06-04 17:39
could start this transaction. am using version 3 as requested

**Comment by rebirthtobi** [comment] 2020-06-04 17:42
`can you log the error in onLoadEnd`

Also can you create an expo snack so as to reproduce the error?
snack.expo.io

**Comment by saladinjake** [comment] 2020-06-04 19:20
Sorry bout the delay .Cant get it to show on the snack.expo.io . here
https://snack.expo.io/@saladinjake/great-chips

**Comment by rebirthtobi** [comment] 2020-06-04 19:23
> Sorry bout the delay .Cant get it to show on the snack.expo.io . here
> https://snack.expo.io/@saladinjake/great-chips

Put your code in there so as to help debug, let us know after

**Comment by saladinjake** [comment] 2020-06-04 19:26
ok

**Comment by saladinjake** [comment] 2020-06-04 21:38
https://snack.expo.io/@saladinjake/paystack-wahala . i was able to reproduce the error on snack. its not even showing the

**Comment by saladinjake** [comment] 2020-06-05 06:15
Goodmorning guys. Can this be resolved? https://snack.expo.io/@saladinjake/paystack-wahala. tried all night to find a fix. it starts off with a loading screen but the form doesnt show up rather this transaction is either invalid or completed. i check my dashboard for any such transaction but i see nothing regarding the transaction. and i cant get to log the onLoadEnd function.

**Comment by saladinjake** [comment] 2020-06-06 13:24
still showing could not start transaction

**Comment by walexanderos** [comment] 2020-06-07 06:45
Hello Everybody,

For anyone experiencing the blank screen issue after the indicator, i resolve mine with the following steps:

![image](https://user-images.githubusercontent.com/36700043/83961837-1687a700-a88f-11ea-9db5-695a960098cf.png)

In the above screen shot from the RN PAYSTACK WEBVIEW module file, channel prop (props.channels) is being assigned to the paystack channels configuration option which accepts only array values (['card', 'bank', 'ussd', 'qr', 'mobile_money']).

![image](https://user-images.githubusercontent.com/36700043/83961955-484d3d80-a890-11ea-820b-b14df2d52cc5.png)

![image](https://user-images.githubusercontent.com/36700043/83961980-a548f380-a890-11ea-8da9-25680afa43bb.png)

So channel props doesn't have a default value neither does it have a user defined value. All i had to do was to assign a channel value and it worked.

![image](https://user-images.githubusercontent.com/36700043/83962046-8ac34a00-a891-11ea-8c87-8ee1448ff6b9.png)

For some unknown reason, i was getting a "Transcation could not start" but after assigning props value, but i couldn't just continue troubleshooting so i had to assign values directly to the config options (currency, channels) in the module file. 

I hope this can be of help to others too.

File Location:
$....\node_modules\react-native-paystack-webview\index.js

**Comment by just1and0** [comment] 2020-06-07 08:00
Thank @walexanderos for noting this, I've made changes and included it in V3.0.8, i have also tested it on expo and it works fine on my end. Do try it out and let me know if the blank screen still comes up.

**Closed by just1and0** 2020-06-07 08:00 UTC

**Comment by just1and0** [comment] 2020-06-07 08:19
@all-contributors please add @walexanderos for bug

**Comment by walexanderos** [comment] 2020-06-07 09:28
> Thank @walexanderos for noting this, I've made changes and included it in V3.0.8, i have also tested it on expo and it works fine on my end. Do try it out and let me know if the blank screen still comes up.

Hello @just1and0 , i just tested and it worked fine. But i will suggest you update your documentation to inform users about specifying channel option since the default channel in the module is only card

![image](https://user-images.githubusercontent.com/36700043/83964741-e64c0280-a8a6-11ea-9af0-336055cb0775.png)

Thank you

**Comment by just1and0** [comment] 2020-06-07 09:46
@walexanderos  Noted, but also keep in mind this is an open-source project, you could just fork the repo and make changes to the project and send a PR, it'll be better so you get recognition for your contributions.

**Comment by just1and0** [comment] 2020-06-07 09:48
also do check out the [contribution guidelines](https://github.com/just1and0/React-Native-Paystack-WebView/blob/master/contribution.md) before making changes.

**Comment by walexanderos** [comment] 2020-06-07 11:23
@just1and0  Alright, i will just do that then. Thank you

**Comment by saladinjake** [comment] 2020-06-07 13:22
followed your instructions still didnt start transaction

**Comment by saladinjake** [comment] 2020-06-07 13:23
using v.3.0.8 and still same issue

**Comment by walexanderos** [comment] 2020-06-07 14:19
@saladinjake, please upgrade to the recent version (3.0.9) . Also can I have a view of how you are using the package

**Comment by saladinjake** [comment] 2020-06-08 13:14
// <View style={{flex: 1}}>
      //   <PaystackWebView
      //     buttonText="Pay Now"
      //     showPayButton={false}
      //     paystackKey="public key"
      //     amount={120000}
      //     billingEmail="paystackwebview@something.com"
      //     billingMobile="09787377462"
      //     billingName="Oluwatobi Shokunbi"
      //     channels={JSON.stringify(['card','ussd'])}
      //     ActivityIndicatorColor="green"
      //     SafeAreaViewContainer={{marginTop: 5}}
      //     SafeAreaViewContainerModal={{marginTop: 5}}
      //     onCancel={() => {
      //       alert('cancelled');
      //     }}
      //     onSuccess={() => {
      //       alert('success');
      //     }}
      //     autoStart={true}
      //   />
      // </View>

**Comment by saladinjake** [comment] 2020-06-08 13:17
if i create a linking out side react-native and say i open the url to a react page on a live server by redirecting a click event a page on the web it works. but on the react native environment it throws the same error

**Comment by walexanderos** [comment] 2020-06-08 14:25
@saladinjake i created a snack [demo ](https://snack.expo.io/@walexanderos/react-native-paystack-webview) which works fine with using v3.0.9 of the package

**Comment by saladinjake** [comment] 2020-06-08 16:01
it does not start transaction tried it on my device

**Comment by saladinjake** [comment] 2020-06-09 21:51
seems to me paystack  api wont let this transaction  start. i read the docs and found a clue to make it work and it scaled thru. thanks for all the digging deep paystack-webview made me do..  i made it work with no issues this time. try making sure the webview renders the paystack-webview once and not multiple times. find a way to communicate to a dedicated server having the paystack code that runs when u inject into the script loaded into webview and .... just make it work. thanks guys. good luck
